root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./src"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
