version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-build:/go/pkg/mod
      - go-cache:/root/.cache/go-build
    ports:
      - ${PORT:-8080}:${PORT:-8080}
      - ${DEBUG_PORT:-8081}:${DEBUG_PORT:-8081}
    env_file:
      - .env

volumes:
  go-build:
  go-cache:
