FROM golang:1.22 as builder

WORKDIR /app

COPY . .

RUN go install github.com/cosmtrek/air@latest

RUN go mod tidy

RUN go mod download

EXPOSE 8080

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]