# Build
FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Test
FROM builder as tester

RUN go test ./...

# Serve
FROM golang:1.22 as serve

# use Air for live reload
RUN go install github.com/cosmtrek/air@latest

COPY --from=builder /app /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app
EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
